### 13. 얼굴 인식

In [6]:
import cv2
KARINA = "images/karina.jpg"
AESPA = "images/aespa.jpg"

In [8]:
face_cascade = cv2.CascadeClassifier("cascade/haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

frame = cv2.imread(AESPA)
gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20,20)) # minNeighbors 값을 키우면 얼굴 감지 정확도 up

eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=10, minSize=(20,20))

if len(faces):
    for face in faces:
        x, y, w, h = face
        cv2.rectangle(frame, (x,y), (x+w, y+h), (255,255,0), 4)

if len(eyes):
    for eye in eyes:
        x, y, w, h = eye
        cv2.rectangle(frame, (x,y), (x+w, y+h), (200,0,255), 3)

cv2.imshow("img", frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 실습. 영상 얼굴인식

In [19]:
import cv2

face_cascade = cv2.CascadeClassifier("cascade/haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

video = cv2.VideoCapture("videos/girl.mp4")
fps = video.get(cv2.CAP_PROP_FPS)

while video.isOpened():
    ret, frame = video.read()

    if not ret:
        break
    
    coppied = frame.copy()
    gray = cv2.cvtColor(coppied, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20,20))
    eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20,20))

    if len(faces):
        for face in faces:
            x, y, w, h = face
            cv2.rectangle(coppied, (x,y), (x+w, y+h), (255,255,0), 4)

    # for eye in eyes:
    #     x, y, w, h = eye
    #     cv2.rectangle(frame, (x,y), (w, h), (200,0,255), 3)

    cv2.imshow("video", coppied)

    if cv2.waitKey(int(1000/fps)) == ord("q"): # 프레임 한개당 초
        break

video.release()
cv2.destroyAllWindows()

### 실습 1. 캠화면 얼굴인식

In [5]:
import cv2

face_cascade = cv2.CascadeClassifier("cascade/haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    exit()

while True:
    ret, frame = cap.read()

    if not ret:
        break

    coppied = frame.copy()
    gray = cv2.cvtColor(coppied, cv2.COLOR_BGR2GRAY)
    
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20,20))
    faces, weights = face_cascade.detectMultiScale2(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20, 20))
    eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=20)
    objects2, weights2 = eye_cascade.detectMultiScale2(gray, scaleFactor=1.1, minNeighbors=5)

    

    if len(faces):
        for (x,y,w,h), weight in zip(faces, weights):
            cv2.rectangle(coppied, (x,y), (x+w, y+h), (0,255,0), 3)
            cv2.putText(coppied, f"face: {weights}", (x,y), cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255), 1)

    # if len(faces):
    #     for i, face in enumerate(faces):
    #         x, y, w, h = face
    #         cv2.rectangle(coppied, (x,y), (x+w, y+h), (0,255,0), 3)
    #         cv2.putText(coppied, f"face: {weights[i]}", (x,y), cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255), 1)


    if len(eyes):
        for i, eye in enumerate(eyes):
            x, y, w, h = eye
            cv2.rectangle(coppied, (x,y), (x+w, y+h), (0,0,0), 2)
            cv2.putText(coppied, f"eye: {weights2[i]}", (x,y), cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255), 1)

    cv2.imshow("Camera", coppied)

    if cv2.waitKey(1) == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [6]:
list_1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
list_2 = [30,40,50]
# 같은 인덱스 원소들끼리 묶어줌 --> 튜플로 새로운 리스트 생성성
print(list(zip(list_1, list_2)))


[([1, 2, 3, 4], 30), ([5, 6, 7, 8], 40), ([9, 10, 11, 12], 50)]


### 실습 2. 눈 영역에 귀여운 눈 덮어 씌우기

In [ ]:
import numpy as np

img = cv2.imread("images/karina.jpg")
left = cv2.imread("images/left_eye.jpg")
right = cv2.imread("images/right_eye.jpg")
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

coppied = img.copy()
gray = cv2.cvtColor(coppied, cv2.COLOR_BGR2GRAY)

eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=10)

indices = np.argsort(eyes[:, 0])
sorted_eyes = eyes[indices]

if len(eyes):
    for i, (x,y,w,h) in enumerate(eyes):
        # cv2.rectangle(coppied, (x,y), (x+w, y+h), (200,0,255), 3)
        print(eyes)
        
        if i % 2 == 0:
            left_resize = cv2.resize(left, (w,h))
            coppied[y:y+h, x:x+w] = left_resize
        else:
            right_resize = cv2.resize(right, (w,h))
            coppied[y:y+eye.shape[0], x:x+eye.shape[1]] = right_resize

cv2.imshow("img", coppied)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[366 247  60  60]
 [253 253  61  61]]
[[366 247  60  60]
 [253 253  61  61]]


In [36]:
eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

cap = cv2.VideoCapture("images/girl.jpg")

while cap.isOpened():
    ret, frame = cap.read()

    if not ret:
        break

    coppied = frame.copy()
    gray = cv2.cvtColor(coppied, cv2.COLOR_BGR2GRAY)

    eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=20)

    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20,20))
    eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(20,20))

    if len(eyes):
        for x, y, w, h in eyes:
            cv2.rectangle(coppied, (x,y), (x+w, y+h), (255,255,0), 2)
            
    cv2.imshow("video", coppied)

    if cv2.waitKey(1) == ord("q"): # 프레임 한개당 초
        break

cap.release()
cv2.destroyAllWindows()

In [37]:
import numpy as np

eye_cascade = cv2.CascadeClassifier("cascade/haarcascade_eye.xml")

img = cv2.imread("images/aespa.jpg")
right_eye = cv2.imread("images/right_eye.jpg")
left_eye = cv2.imread("images/left_eye.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

eyes = eye_cascade.detectMultiScale(
  gray, scaleFactor=1.1, minNeighbors=3, maxSize=(25,25)
)
indices = np.argsort(eyes[:, 0])
sorted_eyes = eyes[indices]

for i, (x,y,w,h) in enumerate(sorted_eyes):
  eye = right_eye
  if i % 2 == 0:
    eye = left_eye
  eye = cv2.resize(eye, (w,h))
  img[y:y+eye.shape[0], x:x+eye.shape[1]] = eye

cv2.imshow("img", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
%pip install ultralytics

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [40]:
from ultralytics import YOLO